# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='permissions'),
        ),
    ]
