# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_mygroup_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=64)),
            ],
            options={
                'permissions': (('access_dashboard', 'access_dashboard'), ('access_log', 'access_log'), ('access_role_manage', 'access_role_manage'), ('access_user_manage', 'access_user_manage')),
            },
        ),
    ]
